id = "rustlang"
title = "The Rust Programming Language"
description = ""
version = "0.1.0"

[[lessons]]
id = "intro"
path = "lessons/ch1/01-introduction/" # Automatically pulls manifest.toml

[[lessons]]
id = "variables"
path = "lessons/ch1/02-variables/"